
export const questions =[
    {
        level : 1,
        description: "Que pandemia paralizó al mundo en el 2020",
        correcta: "COVID 19",
        respuesta1: "Peste Negra",
        respuesta2: "COVID 19",
        respuesta3: "VIH",
        respuesta4: "COVID 2020",
    },

    {
        level : 1,
        description: "Es una Isla Colombiana",
        correcta: "San Andres",
        respuesta1: "Cuba",
        respuesta2: "Aruba",
        respuesta3: "Jamaica",
        respuesta4: "San Andres",
    },
    {
        level : 1,
        description: "Cuál de los siguientes elementos es atraido por un iman",
        correcta: "HIERRO",
        respuesta1: "CARBON",
        respuesta2: "MADERA",
        respuesta3: "PLASTICO",
        respuesta4: "HIERRO",
    },
    {
        level : 1,
        description: "Cuál es un color primario",
        correcta: "AZUL",
        respuesta1: "AZUL",
        respuesta2: "MORADO",
        respuesta3: "VERDE",
        respuesta4: "BLANCO",
    },
    {
        level : 1,
        description: "Cuanto es el resultado de multiplicar un numero por cero",
        correcta: "CERO",
        respuesta1: "EL MISMO NUMERO",
        respuesta2: "INFINITO",
        respuesta3: "CERO",
        respuesta4: "UNO",
    },
    {
        level : 2,
        description: "En que fecha llegó Cristóbal Colón a América",
        correcta: "12 DE OCTUBRE DE 1942",
        respuesta1: "20 DE JULIO DE 1810",
        respuesta2: "12 DE OCTUBRE DE 1942",
        respuesta3: "31 DE DICIEMBRE DE 1942",
        respuesta4: "6 DE MARZO DE 2021",
    },
    {
        level : 2,
        description: "Cuáles son los únicos mamíferos que pueden volar",
        correcta: "MURCIELAGOS",
        respuesta1: "MOSCAS",
        respuesta2: "PALOMAS",
        respuesta3: "MURCIELAGOS",
        respuesta4: "ORNITORRINCOS",
    },
    {
        level : 2,
        description: "En que año llegó el hombre a la Luna",
        correcta: "1969",
        respuesta1: "2000",
        respuesta2: "1900",
        respuesta3: "1969",
        respuesta4: "1996",
    },
    {
        level : 2,
        description: "Cuántos días tiene un año bisiesto",
        correcta: "366",
        respuesta1: "366",
        respuesta2: "360",
        respuesta3: "365",
        respuesta4: "364",
    },
    {
        level : 2,
        description: "Cuántos anillos hay en la bandera olímpica",
        correcta: "CINCO",
        respuesta1: "SEIS",
        respuesta2: "CUATRO",
        respuesta3: "CINCO",
        respuesta4: "DOS",
    },
    
    
]