
export const data =[
    {
        level : 1,
        description: "Que pandemia paralizó al mundo en el 2020",
        correcta: "COVID 19",
        respuesta1: "Peste Negra",
        respuesta2: "COVID 19",
        respuesta3: "VIH",
        respuesta4: "COVID 2020",
    },

    {
        level : 1,
        description: "Es una Isla Colombiana",
        correcta: "San Andres",
        respuesta1: "Cuba",
        respuesta2: "Aruba",
        respuesta3: "Jamaica",
        respuesta4: "San Andres",
    },
    {
        level : 1,
        description: "Cuál de los siguientes elementos es atraido por un iman",
        correcta: "HIERRO",
        respuesta1: "CARBON",
        respuesta2: "MADERA",
        respuesta3: "PLASTICO",
        respuesta4: "HIERRO",
    },
    {
        level : 1,
        description: "Cuál es un color primario",
        correcta: "AZUL",
        respuesta1: "AZUL",
        respuesta2: "MORADO",
        respuesta3: "VERDE",
        respuesta4: "BLANCO",
    },
    {
        level : 1,
        description: "Cuanto es el resultado de multiplicar un numero por cero",
        correcta: "CERO",
        respuesta1: "EL MISMO NUMERO",
        respuesta2: "INFINITO",
        respuesta3: "CERO",
        respuesta4: "UNO",
    },
    {
        level : 2,
        description: "En que fecha llegó Cristóbal Colón a América",
        correcta: "12 DE OCTUBRE DE 1942",
        respuesta1: "20 DE JULIO DE 1810",
        respuesta2: "12 DE OCTUBRE DE 1942",
        respuesta3: "31 DE DICIEMBRE DE 1942",
        respuesta4: "6 DE MARZO DE 2021",
    },
    {
        level : 2,
        description: "Cuáles son los únicos mamíferos que pueden volar",
        correcta: "MURCIELAGOS",
        respuesta1: "MOSCAS",
        respuesta2: "PALOMAS",
        respuesta3: "MURCIELAGOS",
        respuesta4: "ORNITORRINCOS",
    },
    {
        level : 2,
        description: "En que año llegó el hombre a la Luna",
        correcta: "1969",
        respuesta1: "2000",
        respuesta2: "1900",
        respuesta3: "1969",
        respuesta4: "1996",
    },
    {
        level : 2,
        description: "Cuántos días tiene un año bisiesto",
        correcta: "366",
        respuesta1: "366",
        respuesta2: "360",
        respuesta3: "365",
        respuesta4: "364",
    },
    {
        level : 2,
        description: "Cuántos anillos hay en la bandera olímpica",
        correcta: "CINCO",
        respuesta1: "SEIS",
        respuesta2: "CUATRO",
        respuesta3: "CINCO",
        respuesta4: "DOS",
    },
    {
        level : 3,
        description: "Cuál es el río más largo del mundo",
        correcta: "AMAZONAS",
        respuesta1: "AMAZONAS",
        respuesta2: "MAGDALENA",
        respuesta3: "NILO",
        respuesta4: "MISISIPI",
    },
    {
        level : 3,
        description: "Cuántos lados tiene un heptágono",
        correcta: "SIETE",
        respuesta1: "NUEVE",
        respuesta2: "SIETE",
        respuesta3: "SEIS",
        respuesta4: "CINCO",
    },
    {
        level : 3,
        description: "Qué gas liberan las plantas al hacer la fotosíntesis",
        correcta: "OXIGENO",
        respuesta1: "HIDROGENO",
        respuesta2: "OXIGENO",
        respuesta3: "HELIO",
        respuesta4: "CARBONO",
    },
    {
        level : 3,
        description: "Cuál es el primer elemento de la tabla periódica",
        correcta: "HIDROGENO",
        respuesta1: "HIDROGENO",
        respuesta2: "CALCIO",
        respuesta3: "AZUFRE",
        respuesta4: "HELIO",
    },
    {
        level : 3,
        description: "Cuál de estas particulas NO conforman un átomo",
        correcta: "IONES",
        respuesta1: "PROTONES",
        respuesta2: "ELECTRONES",
        respuesta3: "IONES",
        respuesta4: "NEUTRONES",
    },
    {
        level : 4,
        description: "Cuál es el libro sagrado del Islam",
        correcta: "EL CORÁN",
        respuesta1: "EL TORÁ",
        respuesta2: "EL CORÁN",
        respuesta3: "LA BIBLIA",
        respuesta4: "EL TALMUD",
    },
    {
        level : 4,
        description: "Quién descubrió la penicilina",
        correcta: "ALEXANDER FLEMING",
        respuesta1: "EDWARD JENNER",
        respuesta2: "ELKIN PATARROYO",
        respuesta3: "ALEXANDER FLEMING",
        respuesta4: "LOUIS PASTEUR",
    },
    {
        level : 4,
        description: "Qué pigmento da color a nuestra piel",
        correcta: "MELANINA",
        respuesta1: "QUERATINA",
        respuesta2: "DERMIS",
        respuesta3: "SEROTONINA",
        respuesta4: "MELANINA",
    },
    {
        level : 4,
        description: "Quién formuló la Teoría de la Relatividad",
        correcta: "EINSTEIN",
        respuesta1: "MAXWELL",
        respuesta2: "NEWTON",
        respuesta3: "EINSTEIN",
        respuesta4: "HAWKING",
    },
    {
        level : 4,
        description: "Cuál es el planeta más cercano al Sol",
        correcta: "MERCURIO",
        respuesta1: "NEPTUNO",
        respuesta2: "MERCURIO",
        respuesta3: "URANO",
        respuesta4: "VENUS",
    },
    {
        level : 5,
        description: "Cuántos corazones tiene un pulpo",
        correcta: "TRES",
        respuesta1: "DOS",
        respuesta2: "UNO",
        respuesta3: "OCHO",
        respuesta4: "TRES",
    },
    {
        level : 5,
        description: "Quién postuló las leyes del movimiento",
        correcta: "NEWTON",
        respuesta1: "KEPLER",
        respuesta2: "EINSTEIN",
        respuesta3: "HAWKING",
        respuesta4: "NEWTON",
    },
    {
        level : 5,
        description: "Quién fue el último faraón de Egipto",
        correcta: "RAMSÉS III",
        respuesta1: "AKENATÓN",
        respuesta2: "AMENOFIS III",
        respuesta3: "RAMSÉS III",
        respuesta4: "CLEOPATRA VII",
    },
    {
        level : 5,
        description: "Cuál fue la primera civilización humana",
        correcta: "SUMERIA",
        respuesta1: "SUMERIA",
        respuesta2: "ASIRIA",
        respuesta3: "BABILONICA",
        respuesta4: "ACADIA",
    },
    {
        level : 5,
        description: "En que año murió Freddie Mercury",
        correcta: "1991",
        respuesta1: "1980",
        respuesta2: "1991",
        respuesta3: "1981",
        respuesta4: "1990",
    },
    
    
]